ds = io$readData( "tests.trialdata.aat.csv", original = T );
settings = list(
  run_var = "set_id",
  resp_var = "response",
  rt_var = "rt",
  
  fast_drop = 200,
  slow_drop = 2000,
  fast_report = 200,
  slow_report = 2000,
  resp_report = c(1),
  resp_drop = c(2,3,4,NA),
  
  aux_report = c("factor_scores"),
  
  aggregation_factors = c( "appr", "cat" ),
  aggregation_factor_function = function( rts ) {
    return( median( rts ) )
  },
  aggregation_run_function = function( wide ) {
    score = 
      ( wide["score.test.no"] - wide["score.test.yes"] ) -
      ( wide["score.control.no"] - wide["score.control.yes"] );
    return(score);
  }
);

calculatedScores = calculateScores(
  type = "aggregation",
  ds,
  settings
);
io$writeData( "tests.medians.aat.csv", calculatedScores );

# Compare scores generated by calculateScores with those calculated manually
correctScores = io$readData( "tests.medians.aat.csv", original = T );

# Matrix with TRUE  for each matching score, and FALSE if not
matches = data.frame.new();
for( i in 1 : nrow(correctScores) ) {
  correctRow = correctScores[i,];
  calculatedRow = calculatedScores[calculatedScores[,"set_id"] == correctRow[,"set_id"],];
  for( j in names( correctRow ) ) {
    if( !(is.na(correctRow[j]) && is.na(calculatedRow[j])) ) {
      if( 
        (is.na(correctRow[j]) && !is.na(calculatedRow[j])) ||
        (!is.na(correctRow[j]) && is.na(calculatedRow[j])) ||
          correctRow[j] != calculatedRow[j] 
      ) {
        print( paste(
          "Mismatch between correct calculated in",
          "set_id", correctRow[,"set_id"],
          "column", j,
          "correct =", correctRow[,j],
          "calculated =", calculatedRow[,j]
        ) );
        matches[i,j] = FALSE;
      } else {
        matches[i,j] = TRUE;
      }
    } else {
      matches[i,j] = TRUE;
    }
  }
  matches[i,"set_id"] = correctRow[,"set_id"];  
}

io$writeData( "tests.medians.matches.aat.csv", matches );
