ds = io$readData( "tests_dscores.trialdata.iat.csv", original = T );
settings = list(
  type         = "dscore",
  
  run_var      = "set_id",
  resp_var     = "response",
  rt_var       = "rt",
  comp_var     = "block",
  comp_levels  = c( "tar1att1", "tar1att2" ), # Bias calculated towards first element
  
  fast_drop = 200,
  slow_drop = 2000,
  fast_report = 200,
  slow_report = 2000,
  
  resp_drop    = c( "NA", 3, 4 ),
  resp_report  = c( 1 ),
  
  resp_correct = 1,  
  resp_penalty = c( 2 ),
  rt_penalty   = "2sd",
  
  aux_report   = c( 
    # For each compatible and incompatible block
    "correct_n", "correct_mean", "correct_sd", "penalty", "adjusted_mean",
    # Across compatible and incompatible
    "inclusive_sd",
    # Across task
    "task_n"
  )
);

calculatedScores = calculateScores(
  settings[[ "type" ]],
  ds,
  settings,
  verbose = TRUE
);

io$writeData( "tests_dscores.scores.iat.csv", calculatedScores );








# Compare scores generated by calculateScores with those calculated manually
correctScores = io$readData( "tests_medians.scores.aat.csv", original = T );

# Matrix with TRUE  for each matching score, and FALSE if not
matches = data.frame.new();
for( i in 1 : nrow(correctScores) ) {
  correctRow = correctScores[i,];
  calculatedRow = calculatedScores[calculatedScores[,"set_id"] == correctRow[,"set_id"],];
  for( j in names( correctRow ) ) {
    if( !(is.na(correctRow[j]) && is.na(calculatedRow[j])) ) {
      if( 
        (is.na(correctRow[j]) && !is.na(calculatedRow[j])) ||
        (!is.na(correctRow[j]) && is.na(calculatedRow[j])) ||
          correctRow[j] != calculatedRow[j] 
      ) {
        print( paste(
          "Mismatch between correct calculated in",
          "set_id", correctRow[,"set_id"],
          "column", j,
          "correct =", correctRow[,j],
          "calculated =", calculatedRow[,j]
        ) );
        matches[i,j] = FALSE;
      } else {
        matches[i,j] = TRUE;
      }
    } else {
      matches[i,j] = TRUE;
    }
  }
  matches[i,"set_id"] = correctRow[,"set_id"];  
}

io$writeData( "tests_medians.scores.matches.aat.csv", matches );
